### ISSUE TITLE
Public demo ?

### ISSUE THREAD

**Issue by leplatrem** [robbiet480/leaflet-categorized-layers#1]
Could you setup a small demo for your plugin please ? (github pages for ex.)

Thanks !

**Comment by aborruso** [comment]
+1

**Comment by robbiet480** [comment]
Sorry all, totally forgot to do this. Just set a reminder for myself to put a nice demo up this weekend.

**Comment by letmaik** [comment]
+1

**Comment by mirceap** [comment]
+1

**Comment by robbiet480** [comment]
I haven't used this plugin for 3 years now and obviously a demo still hasn't materialized, so sorry for getting your hopes up on this everyone :(
